version: '3.8'
services:
  dashboard-backend:
    build:
      context: ./backend-dashboard
      dockerfile: Dockerfile
    container_name: dashboard-backend
    env_file:
      - ./backend-dashboard/.env.dashboard
    ports:
      - "8001:8000"
    restart: always
    # depends_on eliminado: ahora se conecta a SQL Server externo

  dashboard-frontend:
    build: ./dashboard
    container_name: dashboard-frontend
    env_file:
      - ./dashboard/.env
    ports:
      - "3000:80"
    depends_on:
      - dashboard-backend




