version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    container_name: verificador-sqlserver
    environment:
      - TZ=America/Caracas
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD:-Dit12345*}
    ports:
      - "1433:1433"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD:-Dit12345*} -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build: .
    image: verificador-backend
    container_name: verificador-backend
    environment:
      - TZ=America/Caracas
    env_file: .env
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./static/banners:/code/static/banners
    restart: always

  redis:
    image: redis:7-alpine
    container_name: verificador_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  mssql_data:
