# nginx.conf básico para servir React y hacer proxy al backend
server {
    listen 80;
    client_max_body_size 500M;
    server_name _;

    # Archivos estáticos del React build
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend
    location /api/ {
        proxy_pass http://dashboard-backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Archivos estáticos del backend (banners)
    location /static/ {
        proxy_pass http://dashboard-backend:8000/static/;
    }
}